name: Docs

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests stable
      run: cargo test 
    - name: Benchmarks
      uses: phillyfan1138/gnuplot-action@master
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with: 
        branch: gh-pages
        folder: target/criterion
    - name: Document 
      run: cargo doc
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - name: Publish
      run: |
        cargo bench
        cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty || true